# Generated by Django 4.2.9 on 2025-05-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot_Feedtray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_value', models.CharField(blank=True, max_length=250, null=True)),
                ('intial_value', models.CharField(blank=True, max_length=250, null=True)),
                ('cycle_count', models.CharField(blank=True, max_length=250, null=True)),
                ('remaining_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
