# Generated by Django 5.2 on 2025-05-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pilot_Feedtray',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('base_value', models.CharField(blank=True, max_length=250, null=True)),
                ('intial_value', models.CharField(blank=True, max_length=250, null=True)),
                ('cycle_count', models.CharField(blank=True, max_length=250, null=True)),
                ('remaining_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
