# Generated by Django 4.2.9 on 2025-05-10 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot_feedtray',
            name='cycle_value',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
