# Generated by Django 4.2.9 on 2025-05-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_pilot_feedtray_cycle_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot_feedtray',
            name='cycle_count',
            field=models.CharField(blank=True, default=0, max_length=250, null=True),
        ),
    ]
