# Generated by Django 4.2.9 on 2025-05-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_pilot_feedtray_cycle_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pilot_feedtray',
            name='cycle_count',
            field=models.CharField(blank=True, default='0', max_length=250, null=True),
        ),
    ]
