# Generated by Django 5.2 on 2025-05-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_pilot_feedtray_cycle_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='pilot_feedtray',
            name='is_reset',
            field=models.BooleanField(default=False),
        ),
    ]
