# Generated by Django 5.2 on 2025-05-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_pilot_feedtray_is_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pilot_feedtray',
            name='is_reset',
        ),
    ]
